export const VALID_IN_APP_PREFERENCE_KEYS = [
  "NEW_MESSAGE", "NEW_ORDER", "ORDER_SHIPPED", "ORDER_DELIVERED",
  "CASE_OPENED", "CASE_MESSAGE", "CASE_RESOLVED", "REFUND_ISSUED",
  "CUSTOM_ORDER_REQUEST", "CUSTOM_ORDER_LINK",
  "VERIFICATION_APPROVED", "VERIFICATION_REJECTED",
  "BACK_IN_STOCK", "NEW_REVIEW", "LOW_STOCK", "NEW_FAVORITE",
  "NEW_BLOG_COMMENT", "BLOG_COMMENT_REPLY",
  "NEW_FOLLOWER", "FOLLOWED_MAKER_NEW_LISTING", "FOLLOWED_MAKER_NEW_BLOG",
  "SELLER_BROADCAST", "COMMISSION_INTEREST",
  "LISTING_APPROVED", "LISTING_REJECTED", "ACCOUNT_WARNING",
  "LISTING_FLAGGED_BY_USER", "PAYMENT_DISPUTE", "PAYOUT_FAILED",
] as const;

export const VALID_EMAIL_PREFERENCE_KEYS = [
  "EMAIL_NEW_MESSAGE", "EMAIL_NEW_ORDER", "EMAIL_ORDER_SHIPPED", "EMAIL_ORDER_DELIVERED",
  "EMAIL_CASE_OPENED", "EMAIL_CASE_MESSAGE", "EMAIL_CASE_RESOLVED", "EMAIL_REFUND_ISSUED",
  "EMAIL_CUSTOM_ORDER", "EMAIL_CUSTOM_ORDER_LINK",
  "EMAIL_VERIFICATION_APPROVED", "EMAIL_VERIFICATION_REJECTED",
  "EMAIL_BACK_IN_STOCK", "EMAIL_NEW_REVIEW", "EMAIL_LOW_STOCK", "EMAIL_NEW_FAVORITE",
  "EMAIL_NEW_BLOG_COMMENT", "EMAIL_BLOG_COMMENT_REPLY",
  "EMAIL_NEW_FOLLOWER", "EMAIL_FOLLOWED_MAKER_NEW_LISTING", "EMAIL_FOLLOWED_MAKER_NEW_BLOG",
  "EMAIL_SELLER_BROADCAST", "EMAIL_COMMISSION_INTEREST",
  "EMAIL_LISTING_APPROVED", "EMAIL_LISTING_REJECTED", "EMAIL_ACCOUNT_WARNING",
  "EMAIL_LISTING_FLAGGED_BY_USER", "EMAIL_PAYMENT_DISPUTE", "EMAIL_PAYOUT_FAILED",
] as const;

export const VALID_PREFERENCE_KEYS = [
  ...VALID_IN_APP_PREFERENCE_KEYS,
  ...VALID_EMAIL_PREFERENCE_KEYS,
] as const;

export type InAppNotificationPreferenceKey = (typeof VALID_IN_APP_PREFERENCE_KEYS)[number];
export type EmailNotificationPreferenceKey = (typeof VALID_EMAIL_PREFERENCE_KEYS)[number];
export type NotificationPreferenceKey = (typeof VALID_PREFERENCE_KEYS)[number];

const VALID_EMAIL_PREFERENCE_KEY_SET = new Set<string>(VALID_EMAIL_PREFERENCE_KEYS);

export function isValidEmailPreferenceKey(key: string | null | undefined) {
  return typeof key === "string" && VALID_EMAIL_PREFERENCE_KEY_SET.has(key);
}
