import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { execFileSync } from 'node:child_process';
import { randomUUID, createHash } from 'node:crypto';
import { createOrderZeroDirectSourceFence } from '../scripts/order-zero-direct-release-source.mjs';
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const FLAGS = { productionExecutionAuthorized:false, completeProductionScope:false };
const FINAL = '20260905170000_correct_order_authority_composition';
const LOCK = '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n';
function fixture(t, { complete = false } = {}) {
  const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'order-evidence-fixture-'));fs.chmodSync(root,0o700);
  const directory=path.join(root,'checkout'),channel=path.join(root,'channel'),output=path.join(root,'export');
  for(const d of [directory,channel])fs.mkdirSync(d,{mode:0o700});
  const write=(file,bytes,mode=0o600)=>{fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});fs.writeFileSync(file,bytes,{mode});};
  for(const name of ['order-handoff-common.mjs','order-handoff-evidence.mjs','order-zero-direct-release-source.mjs'])
    write(path.join(directory,'scripts',name),fs.readFileSync(path.join('scripts',name)));
  const names=[...Array.from({length:250},(_,i)=>`${String(20200101000000+i)}_fixture`),FINAL];
  for(const name of names)write(path.join(directory,'prisma/migrations',name,'migration.sql'),'-- fixture-only reviewed SQL\nSELECT 1;\n');
  write(path.join(directory,'prisma/migrations/migration_lock.toml'),LOCK);
  const git=args=>execFileSync('/usr/bin/git',args,{cwd:directory,encoding:'utf8',stdio:['ignore','pipe','pipe'],env:{PATH:'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'}}).trim();
  git(['init','--quiet']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@example.invalid']);
  git(['remote','add','origin','https://github.com/Drewyoung910/grainline.git']);git(['add','.']);git(['commit','--quiet','-m','fixture']);
  const releaseCommit=git(['rev-parse','HEAD']),source=createOrderZeroDirectSourceFence(directory,releaseCommit).capture();
  const npmCli=path.join(root,'npm-cli.js');write(npmCli,'// fixture only\n');
  const runId=String(Math.floor(Math.random()*1e14)+1),sessionId=randomUUID();
  const plan={directory,reviewed:{releaseCommit,sourceCatalogSha256:source.catalogSha256,sourceFenceSha256:hash(fs.readFileSync(path.join(directory,'scripts/order-zero-direct-release-source.mjs'))),nodeSha256:hash(fs.readFileSync(process.execPath)),nodeVersion:process.version,npmCli,npmCliSha256:hash(fs.readFileSync(npmCli)),npmVersion:'10.9.3'},ci:{ciRunId:'456',ciRunAttempt:'1'},context:{releaseCommit,runId,runAttempt:'1',runnerName:'Fixture runner'},scope:'order-compatible-prefix-17',confirmation:'run-reviewed-production-migrations-from-main'};
  write(path.join(channel,'plan.json'),JSON.stringify(plan));
  const state={version:1,supervisorPid:2147483000,workerPid:2147483001,sessionId,releaseCommit,runId,runAttempt:'1',...FLAGS};
  write(path.join(channel,'launch.json'),JSON.stringify({version:1,supervisorPid:state.supervisorPid,releaseCommit,runId,runAttempt:'1',...FLAGS}));
  const phases=complete?['preparing','awaiting-handoff','loading','executing','complete']:['preparing','awaiting-handoff','loading','executing'];
  phases.forEach((phase,i)=>write(path.join(channel,`phase-${i}.json`),JSON.stringify({...state,phase,...(i===0?{workerPid:null,sessionId:null}:{})})));
  // Never exported, even if the value resembles a secret. No actual credentials.
  write(path.join(channel,'capability'),'fixture-private-capability-do-not-export');write(path.join(channel,'ready.json'),'fixture-private-ready-do-not-export');
  if(complete)write(path.join(channel,'result.json'),JSON.stringify({...state,phase:'complete',outcome:'passed',lastActivePhase:'executing',operation:'handoff',failureCode:null,requestedJobId:'123',evidenceUploadProven:false,hostLossDurabilityProven:false,execution:{status:'passed',initialPrefix:0,finalPrefix:17,appliedMemberCount:17,reviewedFunctionCount:36,migrationStatusVerified:true,globalAuthorityVerified:true,finalReadOnlyScopeVerified:true,...FLAGS}}));
  const claim=path.join(root,'.order-release-checkout'),artifacts=path.join(claim,'artifacts'),selected=path.join(artifacts,'order-prefix-ABC123'),journal=path.join(artifacts,'execution-journal-ABC123'),capsule=path.join(artifacts,'execution-capsule-ABC123');
  for(const d of [claim,artifacts,selected,journal,capsule])fs.mkdirSync(d,{mode:0o700});
  write(path.join(claim,'home/private-env'),'fixture-owner-secret-do-not-export');
  if(complete)write(path.join(claim,'checkpoint-5-admitted-complete-graph-import.json'),JSON.stringify({workerPid:state.workerPid,sessionId,state:'admitted-complete',preparationStage:'graph-import',releaseCommit,loadedReleaseGraphProven:true,installedToolchainProven:true,...FLAGS}));
  for(const name of complete?names:[names[0]]){const d=path.join(selected,name);fs.mkdirSync(d,{mode:0o700});write(path.join(d,'migration.sql'),fs.readFileSync(path.join(directory,'prisma/migrations',name,'migration.sql')),0o400);fs.chmodSync(d,0o500);}
  write(path.join(selected,'migration_lock.toml'),LOCK,0o400);if(complete)fs.chmodSync(selected,0o500);
  write(path.join(capsule,'prisma.config.mjs'),`export default ${JSON.stringify({schema:path.join(directory,'prisma/schema.prisma'),migrations:{path:selected}}).slice(0,-1)},datasource:{url:process.env.DIRECT_URL}};\n`,0o400);fs.chmodSync(capsule,0o500);
  const attemptId=randomUUID(),j={version:1,attemptId,releaseCommit,sourceCatalogSha256:source.catalogSha256,initialPrefix:0,prefixCatalogSha256:'a'.repeat(64),stage:complete?'complete':'apply-intent',productionExecutionAuthorized:false};
  write(path.join(journal,'execution.json'),JSON.stringify(j));if(!complete)write(path.join(journal,'execution.lock'),attemptId);
  const hostClaim=path.join(fs.realpathSync('/tmp'),`grainline-order-admission-${process.getuid()}-${runId}-1`);fs.mkdirSync(hostClaim,{mode:0o700});
  t.after(()=>{for(const d of [selected,...names.map(n=>path.join(selected,n)),capsule])if(fs.existsSync(d))fs.chmodSync(d,0o700);fs.rmSync(root,{recursive:true,force:true});fs.rmdirSync(hostClaim);});
  const collect=()=>{try{return {ok:true,value:JSON.parse(execFileSync(process.execPath,['scripts/order-handoff-evidence.mjs',channel,output],{cwd:directory,encoding:'utf8',timeout:30000,env:{PATH:'/usr/bin:/bin',TZ:'UTC',LANG:'C'},stdio:['ignore','pipe','pipe']}))};}catch(error){return{ok:false,stdout:error.stdout,stderr:error.stderr};}};
  return{root,directory,channel,output,selected,capsule,journal,plan,collect,write,names,j};
}
test('evidence exports complete reviewed artifact and safe digests without private channel or home',t=>{
  const f=fixture(t,{complete:true}),result=f.collect();assert.equal(result.ok,true,result.stderr);assert.equal(result.value.outcome,'passed');
  const manifest=JSON.parse(fs.readFileSync(path.join(f.output,'manifest.json')));assert.equal(manifest.files.length,263);
  for(const item of manifest.files){const file=path.join(f.output,item.name),bytes=fs.readFileSync(file);assert.equal(hash(bytes),item.sha256);assert.equal(fs.statSync(file).mode&0o7777,0o600);assert.ok(!bytes.includes('do-not-export'));}
  const binding=JSON.parse(fs.readFileSync(path.join(f.output,'binding.json')));assert.equal(binding.selectedFiles,252);assert.equal(binding.evidenceUploadProven,false);assert.equal(binding.hostLossDurabilityProven,false);
  assert.equal(f.collect().ok,false,'never overwrite an existing export');
});
test('evidence preserves incomplete crash journal and partial staging without inventing completion',t=>{
  const f=fixture(t),before=fs.readFileSync(path.join(f.journal,'execution.lock'));
  f.write(path.join(f.journal,'execution.pending'),JSON.stringify({...f.j,stage:'prefix-verified'}));
  const result=f.collect();assert.equal(result.ok,false);assert.equal(JSON.parse(result.stdout).outcome,'incomplete');
  assert.deepEqual(fs.readFileSync(path.join(f.output,'journal/execution.lock')),before);assert.deepEqual(fs.readFileSync(path.join(f.journal,'execution.lock')),before);
  assert.equal(JSON.parse(fs.readFileSync(path.join(f.output,'binding.json'))).selectedFiles,2);
});
test('evidence refuses secret-shaped fields, arbitrary artifact bytes, links, extra files and live process',t=>{
  for(const mutate of [
    f=>{const p=path.join(f.channel,'phase-3.json'),v=JSON.parse(fs.readFileSync(p));v.ownerUrl='fixture-owner-secret-do-not-export';f.write(p,JSON.stringify(v));},
    f=>{const p=path.join(f.selected,f.names[0],'migration.sql');fs.chmodSync(p,0o600);fs.writeFileSync(p,'fixture-owner-secret-do-not-export');fs.chmodSync(p,0o400);},
    f=>{const p=path.join(f.journal,'execution.lock');fs.unlinkSync(p);fs.symlinkSync(path.join(f.channel,'capability'),p);},
    f=>f.write(path.join(f.journal,'.env'),'fixture-owner-secret-do-not-export'),
    f=>{for(let i=0;i<4;i++){const p=path.join(f.channel,`phase-${i}.json`),v=JSON.parse(fs.readFileSync(p));v.supervisorPid=process.pid;f.write(p,JSON.stringify(v));}},
    f=>{fs.chmodSync(f.selected,0o700);fs.mkdirSync(path.join(f.selected,'20260905180000_unreviewed_correction'),{mode:0o700});},
  ]){const f=fixture(t);mutate(f);const result=f.collect();assert.equal(result.ok,false);assert.equal(fs.existsSync(f.output),false);assert.equal(result.stdout,'');assert.ok(!result.stderr.includes('fixture-owner-secret'));}
});
