CREATE TABLE "SiteMetricsSnapshot" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "avgConversion" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "avgCtr" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "avgRating" DOUBLE PRECISION NOT NULL DEFAULT 3,
  "calculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "SiteMetricsSnapshot_pkey" PRIMARY KEY ("id")
);
