-- Add database-level length caps for bounded text fields.
-- Long-form content fields such as listing descriptions, blog bodies, profile stories,
-- and policy text intentionally remain PostgreSQL text columns.

ALTER TABLE "User" ALTER COLUMN "clerkId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "imageUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "termsVersion" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "shippingName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shippingLine1" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shippingLine2" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shippingCity" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shippingState" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "shippingPostalCode" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "shippingPhone" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "banReason" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "bannedBy" SET DATA TYPE VARCHAR(255);

ALTER TABLE "SellerProfile" ALTER COLUMN "displayName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "city" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "state" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "stripeAccountId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "shipFromName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shipFromLine1" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shipFromLine2" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shipFromCity" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shipFromState" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "shipFromPostal" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "shipFromCountry" SET DATA TYPE VARCHAR(2),
ALTER COLUMN "tagline" SET DATA TYPE VARCHAR(140),
ALTER COLUMN "bannerImageUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "avatarImageUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "workshopImageUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "storyTitle" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "instagramUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "facebookUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "pinterestUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "tiktokUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "websiteUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "guildMasterReviewNotes" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "vacationMessage" SET DATA TYPE VARCHAR(500);

ALTER TABLE "SellerFaq" ALTER COLUMN "question" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "answer" SET DATA TYPE VARCHAR(2000);

ALTER TABLE "Listing" ALTER COLUMN "title" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "currency" SET DATA TYPE VARCHAR(3),
ALTER COLUMN "videoUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "rejectionReason" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "metaDescription" SET DATA TYPE VARCHAR(320);

ALTER TABLE "Photo" ALTER COLUMN "url" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "altText" SET DATA TYPE VARCHAR(200);

ALTER TABLE "Review" ALTER COLUMN "comment" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "sellerReply" SET DATA TYPE VARCHAR(2000);

ALTER TABLE "Message" ALTER COLUMN "body" SET DATA TYPE VARCHAR(5000),
ALTER COLUMN "kind" SET DATA TYPE VARCHAR(50);

ALTER TABLE "ReviewPhoto" ALTER COLUMN "url" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "altText" SET DATA TYPE VARCHAR(200);

ALTER TABLE "Order" ALTER COLUMN "stripeSessionId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "currency" SET DATA TYPE VARCHAR(3),
ALTER COLUMN "shippingTitle" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "buyerEmail" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "buyerName" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shipToLine1" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shipToLine2" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "shipToCity" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shipToState" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "shipToPostalCode" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "shipToCountry" SET DATA TYPE VARCHAR(2),
ALTER COLUMN "stripePaymentIntentId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "stripeChargeId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "stripeApplicationFeeId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "stripeTransferId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "trackingCarrier" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "trackingNumber" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shippingCarrier" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "shippingService" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "taxReversalId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "quotedToLine1" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "quotedToLine2" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "quotedToCity" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "quotedToState" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "quotedToPostalCode" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "quotedToCountry" SET DATA TYPE VARCHAR(2),
ALTER COLUMN "quotedToName" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "quotedToPhone" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "sellerRefundId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "shippoShipmentId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "shippoRateObjectId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "shippoTransactionId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "labelUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "labelCarrier" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "labelTrackingNumber" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "giftNote" SET DATA TYPE VARCHAR(500);

ALTER TABLE "OrderShippingRateQuote" ALTER COLUMN "shipmentId" SET DATA TYPE VARCHAR(255);

ALTER TABLE "OrderPaymentEvent" ALTER COLUMN "stripeEventId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "stripeObjectId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "stripeObjectType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "eventType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "currency" SET DATA TYPE VARCHAR(3),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "reason" SET DATA TYPE VARCHAR(255);

ALTER TABLE "SellerPayoutEvent" ALTER COLUMN "stripePayoutId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "currency" SET DATA TYPE VARCHAR(3),
ALTER COLUMN "failureCode" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "failureMessage" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "stripeEventId" SET DATA TYPE VARCHAR(255);

ALTER TABLE "CartItem" ALTER COLUMN "variantKey" SET DATA TYPE VARCHAR(255);

ALTER TABLE "ListingVariantGroup" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);

ALTER TABLE "ListingVariantOption" ALTER COLUMN "label" SET DATA TYPE VARCHAR(100);

ALTER TABLE "Case" ALTER COLUMN "description" SET DATA TYPE VARCHAR(5000),
ALTER COLUMN "stripeRefundId" SET DATA TYPE VARCHAR(255);

ALTER TABLE "CaseMessage" ALTER COLUMN "body" SET DATA TYPE VARCHAR(5000);

ALTER TABLE "SavedSearch" ALTER COLUMN "query" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "sort" SET DATA TYPE VARCHAR(50);

ALTER TABLE "MakerVerification" ALTER COLUMN "craftDescription" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "guildMasterCraftBusiness" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "portfolioUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "reviewNotes" SET DATA TYPE VARCHAR(2000);

ALTER TABLE "BlogPost" ALTER COLUMN "slug" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "title" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "excerpt" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "coverImageUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "videoUrl" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "metaDescription" SET DATA TYPE VARCHAR(320);

ALTER TABLE "BlogComment" ALTER COLUMN "body" SET DATA TYPE VARCHAR(2000);

ALTER TABLE "NewsletterSubscriber" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(200);

ALTER TABLE "EmailSuppression" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "source" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "eventId" SET DATA TYPE VARCHAR(255);

ALTER TABLE "ResendWebhookEvent" DROP CONSTRAINT "ResendWebhookEvent_pkey",
ALTER COLUMN "svixId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "type" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "lastError" SET DATA TYPE VARCHAR(2000),
ADD CONSTRAINT "ResendWebhookEvent_pkey" PRIMARY KEY ("svixId");

ALTER TABLE "CronRun" DROP CONSTRAINT "CronRun_pkey",
ALTER COLUMN "id" SET DATA TYPE VARCHAR(160),
ALTER COLUMN "jobName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "bucket" SET DATA TYPE VARCHAR(32),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(32),
ADD CONSTRAINT "CronRun_pkey" PRIMARY KEY ("id");

ALTER TABLE "EmailFailureCount" DROP CONSTRAINT "EmailFailureCount_pkey",
ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "lastEventId" SET DATA TYPE VARCHAR(255),
ADD CONSTRAINT "EmailFailureCount_pkey" PRIMARY KEY ("email");

ALTER TABLE "StripeWebhookEvent" DROP CONSTRAINT "StripeWebhookEvent_pkey",
ALTER COLUMN "id" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "type" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "lastError" SET DATA TYPE VARCHAR(2000),
ADD CONSTRAINT "StripeWebhookEvent_pkey" PRIMARY KEY ("id");

ALTER TABLE "Notification" ALTER COLUMN "title" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "body" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "link" SET DATA TYPE VARCHAR(2048);

ALTER TABLE "SellerBroadcast" ALTER COLUMN "message" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "imageUrl" SET DATA TYPE VARCHAR(2048);

ALTER TABLE "CommissionRequest" ALTER COLUMN "title" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(5000),
ALTER COLUMN "timeline" SET DATA TYPE VARCHAR(200);

ALTER TABLE "Metro" ALTER COLUMN "slug" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "state" SET DATA TYPE VARCHAR(50);

ALTER TABLE "AdminAuditLog" ALTER COLUMN "action" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "targetType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "targetId" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "reason" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "undoneBy" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "undoneReason" SET DATA TYPE VARCHAR(1000);

ALTER TABLE "UserReport" ALTER COLUMN "reason" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "details" SET DATA TYPE VARCHAR(2000),
ALTER COLUMN "targetType" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "targetId" SET DATA TYPE VARCHAR(255);
